Repository Arks-Layer/PSNovaTranslations, pull requests merged in 2019-12, with the labels that each got.

#418 Enemy Core fixes
  coverage.py
  rmd/Enemy Cores.json
  rmd/Quests.json
Labels: size/M

#420 I am now super busy, so here's my results
  rmd/Enemies.json
  rmd/Materials.json
  rmd/Promise Orders.json
  rmd/Story 1.json
Labels: size/XL

#423 Fix G-Ga Wonda VH Core
  rmd/Enemy Cores.json
  rmd/Materials.json
Labels: size/XS
