Repository Arks-Layer/PSNovaTranslations, pull requests merged in 2022-02, with the labels that each got.

#441 Saigo no kōken, unless there's error or typo
  rmd/Food.json
  rmd/Materials.json
  rmd/Promise Orders.json
  rmd/Quests.json
  rmd/Shields.json
  rmd/Story 2.json
  rmd/Weapons.json
Labels: size/XXL

#443 Fix weapons.json line 2935
  rmd/Weapons.json
Labels: size/XS

#444 Formatting fixes
  gen_enemy_mats.py
  rmd/Crew.json
  rmd/Help Text.json
  rmd/Story 1.json
  rmd/Story 2.json
Labels: size/S

#445 typo corrections
  rmd/Food.json
  rmd/Weapons.json
Labels: size/S

#446 add new line
  rmd/Story 1.json
Labels: size/XS

#447 Couple of fixes
  rmd/Story 1.json
Labels: size/XS

#448 More fixes
  rmd/Enemies.json
  rmd/Enemy Cores.json
  rmd/Materials.json
  rmd/Promise Orders.json
  rmd/Story 1.json
Labels: size/L

#449 Test fixes
  rmd/Story 1.json
Labels: size/M

#450 Corrections + translations
  rmd/Story 1.json
  rmd/Story 3.json
Labels: size/M

#452 Start of translations of Tutorials
  rmd/Story 1.json
  rmd/Story 2.json
  rmd/Tutorials.json
Labels: size/S

#453 Test fix
  rmd/Tutorials.json
Labels: size/XS

#454 Grammar fixes
  rmd/Story 1.json
  rmd/Story 2.json
Labels: size/L
